-- Align database-side defaults with the Prisma schema. UUID and updatedAt
-- values are generated by Prisma, while the Hydro URL remains a DB default.
ALTER TABLE "export_tasks" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "external_oj_platforms" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "hydro_accounts" ALTER COLUMN "platform_base_url" SET DEFAULT 'https://oj.example.com';
ALTER TABLE "review_reminder_rules" ALTER COLUMN "id" DROP DEFAULT;
